import Head from "next/head";
import Image from "next/image";
import Styles from "../styles/Pages.module.css";
import NavBar from "./components/navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>

      <NavBar />
    </>
  );
}